version: '3'
services:
    app:
        image: golang:1.16.1-alpine
        volumes:
            - .:/go/src/go-with-compose
        working_dir: /go/src/go-with-compose
        command: go run main.go
  
